### PR TITLE
Add Qwant

### PR DESCRIPTION
**Pull request by gabrielelucci**
Just found this app on F-Droid and went peeking into the surprisingly simple source code. I never coded in Kotlin, but looks pretty interesting and not too hard; this app inspired me to learn some of it. 

Peeking into open issues I found a really trivial one (issue #9 ) and decided to quickly fix it. Hope this is welcome, I'm looking forward to contribute more!

(I didn't add the square background mask to the drawable... is it necessary?)

### CODE REVIEW

**Comment by veniosg** [comment]
Thanks for the request! Ideally it wouldd follow the same style as bing/google/yandex - it's actually a rounded square. I think it'd be easy enough to copy one of these, cut out the logo part, and overlay the drawable you created! 

Happy to hear it introduced you to Kotlin! The app was remedying a personal frustration (especially after DDG's last update) and I thought I'd start simple and go from there - no point complicating an app this small :)

**Comment by gabrielelucci** [comment]
Quickly added the background to it.
Problem is, is it worth it to add Qwant if you are working on custom search provider?

**Comment by gabrielelucci** [comment]
And I agree, the newest DDG upgrade sucked a bit... The old DDG app was better, the new one is just a lame WebView browser.

**Comment by veniosg** [comment]
Thanks for updating! I merged it anyway - I guess there's no harm in adding it since it seems popular :)

**Comment by gabrielelucci** [comment]
Pro-tip: work on features on new git branches. Also, bring up new code to an outdated branch using `git rebase` (instead of `git merge`): this way the git history will be a lot more cleaner.

**Comment by veniosg** [comment]
Agreed, I'm only working on master as it's simple enough atm (plus the custom provider is disabled). But I prefer squashing merges, it's even cleaner that way.

**Comment by gabrielelucci** [comment]
It's ok :)

**Pull request merged**
